apiVersion: v1
kind: ServiceAccount
metadata:
  name: calf-42014-aks-istio-identity
  namespace: aks-istio-ingress
  annotations:
    azure.workload.identity/client-id: 0d1dc12c-43ae-47f4-ba0c-9be88faf2d0e
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: aks-istio-ingress
spec:
  selector:
    matchLabels:
      app: default-ingress-backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: default-ingress-backend
    spec:
      serviceAccountName: calf-42014-aks-istio-identity
      containers:
      - name: ingress
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: tls-mount
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: tls-mount
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "istio-tls"
---
apiVersion: v1
kind: Service
metadata:
  name: default-backend-svc
  namespace: aks-istio-ingress
  labels:
    version: "1.0"
spec:
  selector:
    app: default-ingress-backend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  default-calf-42014-local-vs
  namespace: aks-istio-ingress
spec:
  hosts:
  -  istio-default.calf-42014.local
  gateways:
  -  aks-istio-ingress/default-contoso-tech-gw
  http:
  - route:
    - destination:
        host: default-backend-svc
        port:
          number: 80
